-- 创建表结构（在 nav 数据库中执行）

CREATE TABLE IF NOT EXISTS `Site` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `url` VARCHAR(191) NOT NULL,
  `desc` TEXT,
  `category` VARCHAR(191) NOT NULL,
  `color` VARCHAR(191),
  `icon` VARCHAR(191),
  `iconType` VARCHAR(191),
  `customIconUrl` TEXT,
  `titleFont` VARCHAR(191),
  `descFont` VARCHAR(191),
  `titleColor` VARCHAR(191),
  `descColor` VARCHAR(191),
  `titleSize` INT,
  `descSize` INT,
  `isHidden` BOOLEAN NOT NULL DEFAULT false,
  `order` INT NOT NULL DEFAULT 0,
  `type` VARCHAR(191) NOT NULL DEFAULT 'site',
  `parentId` VARCHAR(191),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Category` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL UNIQUE,
  `color` VARCHAR(191),
  `isHidden` BOOLEAN NOT NULL DEFAULT false,
  `order` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `User` (
  `username` VARCHAR(191) NOT NULL PRIMARY KEY,
  `passwordHash` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `GlobalSettings` (
  `id` INT NOT NULL PRIMARY KEY DEFAULT 1,
  `layout` TEXT NOT NULL,
  `config` TEXT NOT NULL,
  `theme` TEXT NOT NULL,
  `searchEngine` VARCHAR(191) NOT NULL DEFAULT 'Google',
  `bingCacheMode` VARCHAR(191) NOT NULL DEFAULT 'keep-all',
  `privatePasswordHash` VARCHAR(191),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Wallpaper` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `url` VARCHAR(191) NOT NULL,
  `type` VARCHAR(191) NOT NULL,
  `filename` VARCHAR(191) NOT NULL,
  `size` INT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `CustomFont` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `family` VARCHAR(191) NOT NULL,
  `url` VARCHAR(191) NOT NULL,
  `provider` VARCHAR(191) NOT NULL DEFAULT 'google',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Todo` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `text` VARCHAR(191) NOT NULL,
  `done` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Countdown` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `label` VARCHAR(191) NOT NULL,
  `date` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
